// Fichas comerciais compartilhadas pela aplicação e pela escola pública no GitHub Pages.
export const catalogItems = [
  {
    id: "dalcomad-kit",
    brand: "dalcomad",
    family: "Kit Porta Pronta",
    title: "Kit Porta Pronta Dalcomad",
    code: "folha + batente/forra + guarnições + vedação; composição a confirmar",
    spec: "Conjunto montado para agilizar a obra, com batente regulável, guarnições/vistas e borracha de vedação; a espuma expansiva entra na instalação conforme especificação.",
    bestFor: "Obra com prazo curto, reforma e cliente que quer reduzir etapas de montagem e acabamento.",
    pitch: "A vantagem é comprar uma solução organizada para a obra: eu confirmo o vão e a composição, e você ganha agilidade sem deixar itens escondidos no orçamento.",
    checks: ["largura, altura e espessura do vão", "alvenaria ou drywall", "linha, cor e revestimento", "usinagem, ferragens e instalação"],
    source: "Guia tático + site oficial",
  },
  {
    id: "dalcomad-master",
    brand: "dalcomad",
    family: "Linhas de portas",
    title: "Linha Master",
    code: "Renolit ou PET-PVC · base dupla de madeira/HDF",
    spec: "Linha de maior foco em acabamento e resistência, com revestimentos Renolit ou PET-PVC e base estruturada; indicada para uma apresentação mais sofisticada.",
    bestFor: "Cliente exigente, ambientes internos de destaque e projetos que valorizam acabamento e resistência à umidade.",
    pitch: "Eu apresentaria a Master quando o acabamento é parte importante da decisão: ela entrega uma leitura mais sofisticada, mas ainda precisamos confirmar cor, medida e composição.",
    checks: ["revestimento Renolit ou PET-PVC", "cor", "preenchimento interno", "medida e sentido de abertura"],
    source: "Guia tático + site oficial",
  },
  {
    id: "dalcomad-slim",
    brand: "dalcomad",
    family: "Linhas de portas",
    title: "Linha Slim",
    code: "acabamento melamínico · medidas especiais sob consulta",
    spec: "Linha de acabamento uniforme e custo-benefício, com base em HDF ou chapa dura; o catálogo de referência trabalha larguras padronizadas e dimensões especiais sob consulta.",
    bestFor: "Quartos, corredores, escritórios e obras que precisam equilibrar preço, padrão e acabamento.",
    pitch: "A Slim é uma boa comparação quando o cliente quer um acabamento organizado sem subir para a especificação mais sofisticada; vamos comparar o que está incluso.",
    checks: ["largura e altura", "acabamento melamínico", "preenchimento", "batente e guarnição"],
    source: "Guia tático + site oficial",
  },
  {
    id: "dalcomad-standard",
    brand: "dalcomad",
    family: "Linhas de portas",
    title: "Linha Standard",
    code: "lâmina natural · base de pinus de reflorestamento",
    spec: "Linha com aparência de madeira natural e foco em equilíbrio entre acabamento, material e compromisso ambiental.",
    bestFor: "Cliente que quer madeira com aparência natural para quartos, salas e ambientes internos.",
    pitch: "Quando a prioridade é sentir a madeira no ambiente, a Standard entra como uma opção natural; eu confirmo a lâmina, a cor e o conjunto antes de fechar.",
    checks: ["lâmina/cor", "medida", "ambiente interno", "batente, guarnição e ferragens"],
    source: "Guia tático + site oficial",
  },
  {
    id: "dalcomad-eco",
    brand: "dalcomad",
    family: "Linhas de portas",
    title: "Linha Eco",
    code: "opção prática para padronização e custo-benefício",
    spec: "Linha de entrada para projetos que precisam de praticidade e uniformidade; acabamento, preenchimento e medida devem ser definidos na ficha do produto.",
    bestFor: "Obras de volume, quartos e clientes que priorizam solução objetiva e orçamento controlado.",
    pitch: "Se o foco é resolver vários ambientes com uma linguagem simples, eu começaria pela Eco e compararia somente o que realmente muda entre as opções.",
    checks: ["acabamento e cor", "preenchimento", "quantidade e medidas repetidas", "itens do kit"],
    source: "Guia tático + site oficial",
  },
  {
    id: "dalcomad-complements",
    brand: "dalcomad",
    family: "Complementos",
    title: "Rodapés e compensados multilaminados",
    code: "rodapés Usual/Ultra · compensados sob especificação",
    spec: "Complementos para aumentar a coerência do acabamento e atender outras necessidades da obra, sem misturar esses itens ao valor da porta sem confirmação.",
    bestFor: "Venda complementar, acabamento da obra e clientes que querem comprar mais etapas em um só atendimento.",
    pitch: "Além da porta, posso conferir se rodapé ou outro complemento resolve uma parte da obra e evita que você precise procurar outro fornecedor.",
    checks: ["altura e acabamento do rodapé", "quantidade de barras", "espessura e aplicação do compensado", "valor separado da porta"],
    source: "Guia tático + site oficial",
  },
  {
    id: "brimak-elite",
    brand: "brimak",
    family: "Linha Elite",
    title: "Portas e janelas Linha Elite",
    code: "pivotantes · correr · venezianas · basculantes",
    spec: "Linha de alumínio com portas de entrada, janelas de 2, 3 e 4 folhas, venezianas, portas de correr e basculantes, em diferentes composições e acabamentos.",
    bestFor: "Entrada principal, dormitórios, fachadas e vãos que pedem iluminação, ventilação ou abertura de correr.",
    pitch: "A Elite reúne soluções para a fachada e para os demais vãos; eu separo a tipologia certa e confirmo medida, folhas, cor e vidro antes da cotação.",
    checks: ["modelo e sistema de abertura", "medida e número de folhas", "cor e tipo de vidro", "puxador, fechadura, persiana ou grade"],
    source: "Catálogo enviado",
    documentHref: "/catalogos/brimak-linha-elite.pdf",
  },
  {
    id: "brimak-super-25",
    brand: "brimak",
    family: "Linha SUPER 25",
    title: "Portas Linha SUPER 25",
    code: "pivotantes · giro · clássicas · correr e balcão",
    spec: "Linha de portas de alumínio com modelos pivotantes, de giro, lambril, clássicos e conjuntos de correr ou balcão com 2, 3, 4 e 6 folhas.",
    bestFor: "Entrada, sala, área de serviço, varanda, sacada e vãos maiores com necessidade de passagem e iluminação.",
    pitch: "A SUPER 25 permite comparar presença na entrada e ganho de passagem nos modelos de correr; definimos primeiro o uso do vão e depois o desenho.",
    checks: ["pivotante, giro, correr ou balcão", "medida e quantidade de folhas", "cor, vidro e lambril", "puxador, fechadura e sentido de abertura"],
    source: "Catálogo enviado",
    documentHref: "/catalogos/brimak-linha-super-25.pdf",
  },
  {
    id: "brimak-l25",
    brand: "brimak",
    family: "Linha L25",
    title: "Portas de alumínio Linha L25",
    code: "camarão · suspensas · clássicas",
    spec: "Linha de portas para uso interno e entrada, com modelos camarão, suspensos e clássicos; as soluções sem giro ajudam a aproveitar melhor a passagem.",
    bestFor: "Divisão de ambientes com pouco espaço, portas internas e entradas que pedem solução funcional e custo-benefício.",
    pitch: "Quando o giro atrapalha, camarão ou suspensa podem liberar a circulação; para a entrada, comparamos os modelos clássicos da mesma linha.",
    checks: ["camarão, suspensa ou clássica", "espaço de recolhimento e vão livre", "medida, cor e vidro", "kit de arremates e ferragens"],
    source: "Catálogo enviado",
    documentHref: "/catalogos/brimak-linha-l25.pdf",
  },
  {
    id: "brimak-pvc",
    brand: "brimak",
    family: "Smart Solutions PVC",
    title: "Portas e janelas de PVC",
    code: "pivotantes · giro · correr · janelas · maxim-ar",
    spec: "Esquadrias com perfis de PVC multicâmaras e reforços internos, incluindo portas pivotantes e de giro, sistemas de correr, janelas e maxim-ar.",
    bestFor: "Projetos que priorizam conforto térmico e acústico, áreas sujeitas à umidade e vãos com solução de correr ou maxim-ar.",
    pitch: "O PVC entra quando conforto e vedação pesam na decisão; eu confirmo a tipologia, o vidro e a instalação adequada para comparar de forma justa.",
    checks: ["sistema de abertura", "medida e reforço do vão", "tipo de vidro e persiana", "cor, ferragens e requisitos de instalação"],
    source: "Catálogo enviado",
    documentHref: "/catalogos/brimak-portas-janelas-pvc.pdf",
  },
  {
    id: "brimak-general-2018",
    brand: "brimak",
    family: "Catálogo geral",
    title: "Linhas Brilhante, Branca e Preta",
    code: "catálogo histórico de produtos · edição 2018",
    spec: "Referência de portas, janelas, venezianas, basculantes e puxadores com acabamentos anodizado brilhante e pintura eletrostática branca ou preta.",
    bestFor: "Identificar famílias e modelos antigos trazidos pelo cliente e preparar uma consulta de equivalência atual.",
    pitch: "Este material ajuda a reconhecer o produto, mas a edição é de 2018; uso como referência e confirmo a versão atual antes de prometer disponibilidade.",
    checks: ["modelo e código reconhecido", "linha e acabamento", "medida, vidro e puxador", "equivalência, disponibilidade e prazo atuais"],
    source: "Catálogo enviado",
    documentHref: "/catalogos/brimak-catalogo-2018.pdf",
  },
  {
    id: "destak-kit",
    brand: "destak",
    family: "Kit porta pronta",
    title: "Kit Porta Pronta",
    spec: "Porta de madeira com batente e guarnição regulável; soluções para alvenaria e drywall.",
    bestFor: "Prazo curto, reforma e cliente que valoriza instalação organizada.",
    pitch: "Você compra uma solução mais completa e reduz etapas de montagem e acabamento na obra.",
    checks: ["tipo de parede", "vão e sentido de abertura", "cor e acabamento", "fechadura e ferragens"],
    source: "Catálogo + site oficial",
  },
  {
    id: "destak-euromax",
    brand: "destak",
    family: "Madeira",
    title: "Linha Euromax",
    code: "lisa ou frisada · batente de aço primer preto",
    spec: "Portas de madeira lisas e frisadas, com opções de batente de aço e medidas catalogadas de 60 a 100 cm.",
    bestFor: "Obras que precisam de padronização, resistência do batente e acabamento escuro.",
    pitch: "A Euromax permite manter a linguagem de madeira e escolher entre lisa ou frisada sem complicar a especificação.",
    checks: ["medida 60/70/80/90/100", "batente preto", "modelo liso ou frisado", "disponibilidade"],
    source: "Catálogo enviado",
  },
  {
    id: "destak-construmax",
    brand: "destak",
    family: "Madeira",
    title: "Linha Construmax",
    code: "lisa ou frisada · batente de aço branco",
    spec: "Portas de madeira lisas e frisadas com batente de aço e pintura branca de acabamento.",
    bestFor: "Ambientes claros e obras que querem um conjunto mais neutro.",
    pitch: "Aqui a porta já conversa com uma obra clara e o batente branco ajuda a manter o conjunto visual mais leve.",
    checks: ["vão", "cor branca", "modelo liso ou frisado", "fechadura"],
    source: "Catálogo enviado",
  },
  {
    id: "destak-colors",
    brand: "destak",
    family: "Acabamentos",
    title: "Cores e base para pintura",
    code: "mogno · branco · angelim · cerejeira · imbuia · HDF",
    spec: "O catálogo aponta cores de madeira e HDF para pintura; o site também apresenta lisas e entalhadas em madeira.",
    bestFor: "Cliente que começa pela cor, pelo ambiente ou pela combinação com piso e móveis.",
    pitch: "Vamos escolher primeiro a linguagem do ambiente; depois travamos modelo, batente e acabamento para o orçamento ficar comparável.",
    checks: ["amostra/cor exata", "luz do ambiente", "disponibilidade", "compatibilidade com batente"],
    source: "Catálogo + site oficial",
  },
  {
    id: "destak-sliding",
    brand: "destak",
    family: "Correr e complementos",
    title: "Trilho de alumínio e rodapé MDF Ultra",
    code: "trilho · mogno, branco, angelim, cerejeira e imbuia",
    spec: "O catálogo apresenta trilho de alumínio para portas de correr e rodapé MDF Ultra com acabamento melamínico.",
    bestFor: "Otimização de espaço e venda complementar de acabamento.",
    pitch: "Se a prioridade é liberar área de circulação, a solução de correr pode ser mais coerente; já o rodapé fecha o acabamento da obra.",
    checks: ["parede livre para correr", "comprimento do trilho", "cor", "rodapé necessário"],
    source: "Catálogo enviado",
  },
  {
    id: "casmavi-portals",
    brand: "casmavi",
    family: "Portais de abrir",
    title: "Realeza, Duquesa, Alteza e Marquesa",
    code: "com ou sem grade; duplo ou abrir",
    spec: "Portais de duas folhas, com modelos com grade e variações de medida final; linhas fortes para entrada e área social.",
    bestFor: "Entrada ampla, fachada e cliente que quer impacto visual.",
    pitch: "Em uma entrada maior, o portal entrega presença e pode ser escolhido entre uma leitura mais clássica, com grade, ou mais limpa.",
    checks: ["número de folhas", "medida final", "grade", "tipo de batente/portal"],
    source: "Catálogo enviado",
  },
  {
    id: "casmavi-opening",
    brand: "casmavi",
    family: "Portas de abrir",
    title: "Americana, Barbara, Mexicana, Milênio, Tuolinho, Florida e Córdoba",
    code: "modelos catalogados em 2 folhas",
    spec: "Família de portas de abrir com opções clássicas, com trava externa, desenhos e combinações de madeira.",
    bestFor: "Entrada ou área social com abertura convencional e escolha estética.",
    pitch: "Quando o cliente não precisa de pivotante, a abertura tradicional oferece mais simplicidade; escolhemos o desenho que conversa com a fachada.",
    checks: ["sentido de abertura", "folga lateral", "modelo", "trava/fechadura"],
    source: "Catálogo enviado",
  },
  {
    id: "casmavi-pivot",
    brand: "casmavi",
    family: "Pivotantes",
    title: "Couro, Clássica, Barcelona, Mix, Egito e Detalhe",
    code: "folhas de 0,72 a 1,22 m em várias séries",
    spec: "Modelos pivotantes com opções montadas em batente caixa 14 e com pivô, além de versões para vidro e arco.",
    bestFor: "Entrada principal e área social com foco em presença, proporção e desenho.",
    pitch: "A pivotante muda a leitura da entrada; primeiro definimos proporção e abertura, depois escolhemos textura, vidro, arco ou grade.",
    checks: ["vão estrutural", "altura e largura da folha", "pivô e batente", "vidro/arco/grade"],
    source: "Catálogo enviado",
  },
  {
    id: "casmavi-glass",
    brand: "casmavi",
    family: "Pivotantes para vidro",
    title: "BBB, Barcelona, Couro longo e Mexicana para vidro",
    code: "vidro reto, arco, 3, 4, 5 ou 7 vidros",
    spec: "Variações com vidro em arco, friso metálico, grade e diferentes composições de vidros.",
    bestFor: "Cliente que quer iluminação, desenho de fachada ou integração visual.",
    pitch: "O vidro pode trazer luz e leveza; vamos decidir se o cliente quer mais transparência, mais desenho ou mais privacidade.",
    checks: ["tipo de vidro", "quantidade de vidros", "arco ou reto", "grade/friso"],
    source: "Catálogo enviado",
  },
  {
    id: "casmavi-special",
    brand: "casmavi",
    family: "Especiais",
    title: "Ripada, Suíça, Madri, Toquio, Fortaleza, Catalunha e Maceió",
    code: "linhas especiais e contemporâneas",
    spec: "Modelos de destaque do catálogo para projetos que pedem textura, friso, desenho ou composição diferenciada.",
    bestFor: "Cliente que já tem uma referência visual ou quer sair do padrão.",
    pitch: "Aqui vale vender o desenho: descubro a referência do cliente e confirmo o modelo exato antes de falar em composição e prazo.",
    checks: ["referência visual", "modelo/código", "medida especial", "prazo de fabricação"],
    source: "Catálogo enviado",
  },
  {
    id: "casmavi-sliding",
    brand: "casmavi",
    family: "Correr",
    title: "Correr quadriculada, panorâmica e BBB friso preto",
    code: "2, 3 ou 4 folhas; reto ou arco",
    spec: "Portas de correr e esquadrias com dimensões catalogadas até conjuntos amplos; opções retas e em arco.",
    bestFor: "Otimização de espaço, vãos maiores e ambientes que precisam de abertura ampla.",
    pitch: "A solução de correr economiza área de giro; no vão maior, comparamos folhas, desenho e medida final antes de fechar.",
    checks: ["comprimento do trilho", "número de folhas", "reto/arco", "medida final"],
    source: "Catálogo enviado",
  },
  {
    id: "casmavi-folding",
    brand: "casmavi",
    family: "Camarão e veneziana",
    title: "Camarão, bang-bang, holandesa e veneziana",
    code: "2 almofadas, 2/12/16 vidros e variações",
    spec: "Portas camarão e venezianas de passagem, armário, bang-bang e holandesa em diferentes composições.",
    bestFor: "Quartos, banheiros, áreas de passagem, armários e situações de pouco espaço.",
    pitch: "Quando o giro atrapalha, a camarão ou a veneziana pode entregar circulação e ventilação com uma linguagem mais leve.",
    checks: ["espaço de recolhimento", "ventilação/privacidade", "número de vidros", "batente e ferragens"],
    source: "Catálogo enviado",
  },
  {
    id: "casmavi-windows",
    brand: "casmavi",
    family: "Janelas e vitrôs",
    title: "Venezianas, vitrô de correr e maxi-ar",
    code: "2/3/4/6 folhas; reto, arco, quadriculado ou panorâmico",
    spec: "Janelas e venezianas de abrir, guilhotina e correr; vitrôs quadriculados, panorâmicos e maxi-ar.",
    bestFor: "Iluminação, ventilação, quartos, cozinhas, lavanderias e fachadas.",
    pitch: "Definimos primeiro ventilação, luz e privacidade; depois escolhemos folhas, grade, arco e tipo de abertura.",
    checks: ["abertura", "folhas", "grade", "medida e arco"],
    source: "Catálogo enviado",
  },
  {
    id: "casmavi-complements",
    brand: "casmavi",
    family: "Complementos",
    title: "Batentes, kit de correr, rodapés e guarnições",
    code: "batentes duplos, caixilho, trilho e perfis sob medida",
    spec: "O catálogo inclui batentes para vidro, arco, caixilho lateral, kit de correr, rodapés e várias guarnições.",
    bestFor: "Aumentar ticket e evitar que o cliente precise comprar partes em lugares diferentes.",
    pitch: "Antes de fechar, vou conferir se o conjunto precisa de batente, guarnição, trilho, rodapé ou complemento para ficar pronto na obra.",
    checks: ["o que acompanha", "perfil e medida", "acabamento", "itens separados"],
    source: "Catálogo enviado",
  },
  {
    id: "aluan-l30",
    brand: "aluan",
    family: "Portas Linha 30",
    title: "Premium, Palheta e Panorâmica",
    code: "Linha 30",
    spec: "Família indicada no site oficial; o catálogo visual apresenta lambril L30, premium pivotante e panorâmica de 2/3 folhas.",
    bestFor: "Cliente que quer alumínio com presença visual e opções de abertura maiores.",
    pitch: "Na Linha 30 eu começaria pela aparência e pela abertura; depois confirmo a composição e a medida disponíveis.",
    checks: ["modelo", "cor", "folhas", "medida e abertura"],
    source: "Catálogo + site oficial",
  },
  {
    id: "aluan-l25",
    brand: "aluan",
    family: "Portas Linha 25 / Master",
    title: "Lambril, friso, vidro, visor e pivotante",
    code: "preta e branca no catálogo/site",
    spec: "Lambril com puxador, friso, vidro, porta social, basculante, pivotante, vidro duplo e visor.",
    bestFor: "Portas de giro, sociais ou pivotantes em alumínio com leitura mais limpa.",
    pitch: "A Linha 25 permite comparar uma porta mais fechada, com vidro, friso ou visor sem sair da mesma família.",
    checks: ["modelo e puxador", "vidro/visor", "cor", "abertura e medida"],
    source: "Catálogo + site oficial",
  },
  {
    id: "aluan-balcony",
    brand: "aluan",
    family: "Portas balcão",
    title: "Veneziana, vitrô e quadriculada",
    code: "3 ou 6 folhas; móveis ou fixas conforme modelo",
    spec: "Portas balcão venezianas e vitrôs em composições de 3 e 6 folhas, com opções de vidro e quadriculado.",
    bestFor: "Cozinha, sala, lavanderia e vãos que pedem luz, ventilação e acesso ao exterior.",
    pitch: "Para balcão, a decisão é entre ventilação, privacidade e passagem; por isso número de folhas e grade entram cedo na conversa.",
    checks: ["3 ou 6 folhas", "veneziana/vitrô", "grade", "cor e vão"],
    source: "Catálogo + site oficial",
  },
  {
    id: "aluan-windows",
    brand: "aluan",
    family: "Janelas e venezianas",
    title: "Linha Master: 2, 3 ou 4 folhas",
    code: "com ou sem grade",
    spec: "Janelas e venezianas móveis com opções com e sem grade; o site oficial destaca branco e preto na Linha Master.",
    bestFor: "Quartos e ambientes que precisam equilibrar ventilação e privacidade.",
    pitch: "Vamos separar o que precisa abrir do que pode ficar fixo e escolher grade apenas onde ela realmente ajuda.",
    checks: ["folhas móveis", "com/sem grade", "cor", "medida do vão"],
    source: "Catálogo + site oficial",
  },
  {
    id: "aluan-maxiar",
    brand: "aluan",
    family: "Vitrô e Maxi-Ar",
    title: "Master L25: 1 ou 2 seções",
    code: "com ou sem grade",
    spec: "Vitrô maxi-ar em 1 e 2 seções, com ou sem grade; indicado para ventilação e vãos menores ou modulados.",
    bestFor: "Banheiro, cozinha, lavanderia e ambientes que precisam de ventilação controlada.",
    pitch: "O maxi-ar resolve ventilação sem exigir uma abertura de giro grande; confirmo seção, grade e medida para encaixar no ambiente.",
    checks: ["1 ou 2 seções", "com/sem grade", "cor", "posição e medida"],
    source: "Catálogo + site oficial",
  },
  {
    id: "aluan-giro",
    brand: "aluan",
    family: "Portas de giro",
    title: "Social, vestiário, palheta, basculante e fixa",
    code: "Linha 25 · preto, branco e brilhante no site",
    spec: "Portas de giro para usos distintos, incluindo social, vestiário, palheta, basculante e fixa.",
    bestFor: "Quartos, banheiros, áreas internas, vestiários e obras de volume.",
    pitch: "Aqui a prioridade é a função: passagem, ventilação, privacidade ou fixação. A estética vem depois sem perder a praticidade.",
    checks: ["uso do ambiente", "ventilação", "tipo de abertura", "cor e medida"],
    source: "Catálogo + site oficial",
  },
  {
    id: "aluan-modular",
    brand: "aluan",
    family: "Vitrô e veneziana modular",
    title: "2/4 folhas e veneziana 3/6 folhas",
    code: "com ou sem grade; preta, branca e brilhante",
    spec: "Linha Modular com vitrôs de 2 ou 4 folhas e venezianas de 3 ou 6 folhas, com ou sem grade.",
    bestFor: "Obras com repetição de vãos, orçamento objetivo e necessidade de padronização.",
    pitch: "Para volume, a modular ajuda a manter padrão, prazo de especificação e comparação de peças.",
    checks: ["quantidade", "folhas e grade", "cor", "medidas repetidas"],
    source: "Catálogo + site oficial",
  },
  {
    id: "aluan-l16",
    brand: "aluan",
    family: "Basculante e Maxi-Ar",
    title: "Linha 16",
    code: "branca, preta e brilhante no catálogo/site",
    spec: "Basculante L16 e maxi-ar em 1 ou 2 seções, com variações de acabamento mostradas no catálogo e canal oficial.",
    bestFor: "Ambientes de ventilação, obras de volume e soluções compactas.",
    pitch: "A Linha 16 é uma opção funcional quando ventilação e custo-benefício pesam mais que uma porta de destaque.",
    checks: ["basculante ou maxi-ar", "1/2 seções", "cor", "medida"],
    source: "Catálogo + site oficial",
  },
  {
    id: "aluan-abrigo",
    brand: "aluan",
    family: "Abrigo L25",
    title: "Guarnição e portinhola",
    code: "Abrigo L25",
    spec: "Família de abrigo com guarnição e portinhola, apresentada no canal oficial e no catálogo.",
    bestFor: "Áreas técnicas, abrigo e fechamento funcional.",
    pitch: "É uma solução de fechamento específico; confirmo o vão e o que precisa ficar acessível antes de cotar.",
    checks: ["uso e acesso", "medida", "guarnição", "portinhola"],
    source: "Catálogo + site oficial",
  },
  {
    id: "brasil-sublime-wood",
    brand: "brasil",
    family: "Alumínio amadeirado",
    title: "Sublime Amadeirado",
    code: "Perfil 32 · catálogo 2026 · páginas 04 a 09",
    spec: "Linha de alumínio amadeirado com portas pivotantes, lambri e ripadas; indicada para levar aparência de madeira a uma solução de alumínio.",
    bestFor: "Entrada, fachada e cliente que quer estética amadeirada com a lógica de uma esquadria de alumínio.",
    pitch: "Eu usaria a Sublime Amadeirado quando a aparência da madeira é importante, mas o projeto pede uma solução de alumínio; vamos confirmar modelo, medida e acabamento.",
    checks: ["modelo pivotante, lambri ou ripado", "perfil 32", "medida e lado", "acabamento e puxador"],
    source: "Catálogo enviado",
  },
  {
    id: "brasil-sublime-black",
    brand: "brasil",
    family: "Alumínio preto",
    title: "Sublime Black",
    code: "Perfil 32 · portas e janelas",
    spec: "Linha preta de perfil 32, com opções para portas, janelas e composições de destaque; o canal oficial também apresenta modelos ACM pivotantes e vidro miniboreal.",
    bestFor: "Projetos contemporâneos, fachada escura e cliente que quer contraste e presença visual.",
    pitch: "A Sublime Black funciona quando o preto precisa aparecer como parte do projeto; eu separo o modelo certo e confirmo vidro, puxador e medida.",
    checks: ["modelo e abertura", "vidro/privacidade", "puxador", "medida, cor e disponibilidade"],
    source: "Catálogo + site oficial",
  },
  {
    id: "brasil-premium-black",
    brand: "brasil",
    family: "Alumínio preto",
    title: "Premium Black",
    code: "Perfil 25 · catálogo 2026 · páginas 20 a 40",
    spec: "Linha de alumínio preto em perfil 25, com variedade para portas, janelas e esquadrias de maior presença.",
    bestFor: "Cliente que quer acabamento preto e variedade de modelos sem partir necessariamente para o perfil 32.",
    pitch: "A Premium Black é uma alternativa para manter a linguagem preta e comparar a solução de forma mais objetiva por modelo e perfil.",
    checks: ["perfil 25", "tipo de porta/janela", "vidro e grade", "vão e acabamento"],
    source: "Catálogo enviado",
  },
  {
    id: "brasil-facility-black",
    brand: "brasil",
    family: "Alumínio preto",
    title: "Facility Black",
    code: "Perfil 20 nas janelas · perfil 25 nas portas",
    spec: "Linha preta com perfis diferentes para janelas e portas, ajudando a montar uma solução funcional para ambientes variados.",
    bestFor: "Obra residencial que precisa padronizar portas e janelas sem tratar todos os vãos como o mesmo produto.",
    pitch: "A Facility permite organizar a obra por função: janela com um perfil, porta com outro, mantendo a leitura preta do conjunto.",
    checks: ["janela ou porta", "perfil aplicável", "folhas, grade e vidro", "medidas repetidas"],
    source: "Catálogo enviado",
  },
  {
    id: "brasil-white-lines",
    brand: "brasil",
    family: "Alumínio branco",
    title: "Sublime, Premium e Facility Brancas",
    code: "Perfis 32, 25 e 20/25 conforme linha",
    spec: "Famílias em alumínio branco para portas, janelas e composições mais neutras; o perfil muda conforme a linha e o produto.",
    bestFor: "Ambiente claro, obra tradicional e cliente que quer uma esquadria discreta e fácil de combinar.",
    pitch: "Aqui eu não escolheria só pela cor: separo Sublime, Premium ou Facility conforme o vão, a função e a composição que o cliente precisa.",
    checks: ["linha e perfil", "tipo de abertura", "vidro/grade", "medida e prazo"],
    source: "Catálogo enviado",
  },
  {
    id: "brasil-soft",
    brand: "brasil",
    family: "Alumínio branco",
    title: "Linha Soft",
    code: "Perfil 16 nas janelas · perfil 25 nas portas",
    spec: "Linha branca para portas e janelas, com perfil 16 nas janelas e perfil 25 nas portas conforme o índice do catálogo.",
    bestFor: "Projetos que precisam de uma solução mais objetiva para janelas e portas de uso cotidiano.",
    pitch: "A Soft entra bem quando a prioridade é resolver com simplicidade; ainda assim confirmo medida, abertura, vidro e o que acompanha.",
    checks: ["janela ou porta", "perfil", "folhas e abertura", "vidro e acabamento"],
    source: "Catálogo enviado",
  },
  {
    id: "brasil-steel",
    brand: "brasil",
    family: "Aço",
    title: "Inove e Evo",
    code: "Inove e Evo · material e acabamento por código",
    spec: "Famílias de aço para portas e janelas. O catálogo e o canal atual apresentam acabamentos diferentes, incluindo Evo com primer branco; conferir proteção, pintura final e composição na ficha da variante.",
    bestFor: "Cliente que prioriza resistência do aço, obra funcional e orçamento que pede uma alternativa ao alumínio.",
    pitch: "Se o aço faz mais sentido pela resistência e pelo orçamento, eu comparo Inove e Evo pela composição, medida e acabamento confirmados.",
    checks: ["Inove ou Evo", "medida e abertura", "pintura/acabamento", "vidro, grade e prazo"],
    source: "Catálogo enviado",
  },
  {
    id: "brasil-steel-primer",
    brand: "brasil",
    family: "Aço",
    title: "Universal e Max",
    code: "Aço primer · conferir acabamento final",
    spec: "Linhas de aço primer apresentadas no catálogo, úteis quando a especificação exige uma base que ainda precisa ser finalizada ou confirmada.",
    bestFor: "Obra que já tem definição de pintura/acabamento e cliente que aceita uma solução em aço primer.",
    pitch: "Aqui eu confirmaria primeiro o acabamento final e a responsabilidade pela pintura; só depois compararia o valor com uma linha pronta.",
    checks: ["Universal ou Max", "acabamento primer", "pintura final", "medida e ferragens"],
    source: "Catálogo enviado",
  },
  {
    id: "brasil-complements",
    brand: "brasil",
    family: "Complementos",
    title: "Alçapão, maxi-ar, porta balcão e tela mosquiteira",
    code: "soluções complementares do catálogo/site",
    spec: "O mix inclui soluções para acesso técnico, ventilação, integração de ambientes e proteção contra insetos; cada item tem composição própria.",
    bestFor: "Aumentar ticket em obras com janelas, áreas técnicas, cozinha, lavanderia e ambientes integrados.",
    pitch: "Antes de finalizar, posso conferir se a obra precisa de algum complemento: ventilação, acesso técnico, porta balcão ou tela mosquiteira.",
    checks: ["tipo de complemento", "medida do vão", "abertura e ventilação", "itens que acompanham"],
    source: "Catálogo + site oficial",
  },
  {
    id: "crv-nobre",
    brand: "crv",
    family: "Alumínio premium",
    title: "Nobre e Nobre Black",
    code: "portas pivotantes, panorâmicas, lambri e janelas integradas",
    spec: "Linha premium de alumínio com fecho embutido na cor, requadros robustos, maior variedade de pivotantes, opções panorâmicas e puxadores modernos.",
    bestFor: "Entrada principal, fachada contemporânea e cliente que valoriza design, presença e acabamento.",
    pitch: "A Nobre é para quando a porta precisa participar da arquitetura; primeiro defino proporção e abertura, depois confirmo cor, vidro, puxador e medida.",
    checks: ["Nobre ou Nobre Black", "pivotante, lambri ou panorâmica", "vidro e fechadura", "vão livre e requadro"],
    source: "Catálogo enviado",
  },
  {
    id: "crv-classic",
    brand: "crv",
    family: "Alumínio",
    title: "Classic, Classic Plus+ e versões Black",
    code: "fecho embutido · perfis robustos · vidro com borracha EPDM",
    spec: "Famílias de alumínio que combinam acabamento superior, custo-benefício, estabilidade, deslizamento suave e opções prontas para instalar conforme o produto.",
    bestFor: "Cliente que quer alumínio com boa apresentação sem necessariamente partir para a linha premium Nobre.",
    pitch: "Na Classic eu consigo montar uma comparação equilibrada: mesma função, linhas diferentes, e o cliente entende o que muda em acabamento e composição.",
    checks: ["Classic, Plus+ ou Black", "porta/janela/balcão", "vidro, grade e folhas", "requadro e medida"],
    source: "Catálogo enviado",
  },
  {
    id: "crv-standard-aluminum",
    brand: "crv",
    family: "Alumínio",
    title: "Standard Alumínio",
    code: "social slim, lambri, mista, veneziana, janelas e vitrôs",
    spec: "Linha de alumínio com variedade para portas sociais, lambri, mistas, venezianas, janelas de correr e vitrôs maxi-ar.",
    bestFor: "Obra residencial, banheiros, quartos, cozinha e projetos com repetição de vãos.",
    pitch: "A Standard ajuda a resolver a obra por função: passagem, ventilação, iluminação ou privacidade. Depois confirmo a folha e o conjunto correto.",
    checks: ["tipo de produto", "folhas e grade", "vidro", "medida, lado e requadro"],
    source: "Catálogo enviado",
  },
  {
    id: "crv-ideal",
    brand: "crv",
    family: "Aço premium",
    title: "Ideal e Ideal Black",
    code: "aço galvanizado · visual clean · fecho embutido",
    spec: "Linha premium de aço acabado com design diferenciado, robustez, resistência, sistema de correr suave e menos elementos aparentes.",
    bestFor: "Cliente que quer resistência do aço sem abrir mão de uma aparência mais limpa e atual.",
    pitch: "A Ideal é uma forma de mostrar que aço não precisa significar acabamento pesado; vamos comparar visual, abertura e medida com o alumínio.",
    checks: ["Ideal ou Ideal Black", "pivotante, abrir ou correr", "fecho e puxador", "medida e vidro"],
    source: "Catálogo enviado",
  },
  {
    id: "crv-inova",
    brand: "crv",
    family: "Aço custo-benefício",
    title: "Inova e Inova Black",
    code: "aço acabado · fecho sobreposto · vidro instalado conforme modelo",
    spec: "Linha de aço voltada a economia aliada à qualidade, com opções para vários ambientes e segurança do aço galvanizado.",
    bestFor: "Cliente sensível a preço, obra de volume e comparação entre aço e alumínio.",
    pitch: "Se a prioridade é custo-benefício, a Inova merece entrar na comparação; eu só preciso igualar medida, vidro e composição antes de falar em preço.",
    checks: ["Inova ou Inova Black", "vidro e grade", "medida e abertura", "composição do conjunto"],
    source: "Catálogo enviado",
  },
  {
    id: "crv-aciaco",
    brand: "crv",
    family: "Aço",
    title: "Aciaço e Standard Aço",
    code: "aço branco, preto ou primer conforme a linha",
    spec: "Famílias de aço do catálogo para portas, janelas, venezianas, vitrôs, alçapões e soluções de obra; acabamento e composição variam por linha.",
    bestFor: "Obra funcional, ambientes de serviço e clientes que querem alternativas em aço por medida e orçamento.",
    pitch: "Aqui eu começo pela função do ambiente e pelo acabamento desejado; depois confiro qual família de aço realmente atende o vão.",
    checks: ["Aciaço ou Standard Aço", "branco, preto ou primer", "grade, vidro e folhas", "medida, lado e prazo"],
    source: "Catálogo enviado",
  },
  {
    id: "crv-windows",
    brand: "crv",
    family: "Janelas e vitrôs",
    title: "Correr, venezianas, integradas e maxi-ar",
    code: "2, 3, 4 ou 6 folhas conforme a família",
    spec: "O catálogo reúne janelas de correr, integradas, venezianas, vitrôs basculantes e maxi-ar, com opções de grade, vidro e folhas móveis.",
    bestFor: "Quartos, cozinha, lavanderia, banheiro, fachadas e obras com vãos repetidos.",
    pitch: "Para janela, eu não começo pelo desenho: começo por luz, ventilação e privacidade, e então escolho folhas, grade e abertura.",
    checks: ["correr, veneziana ou maxi-ar", "folhas móveis/fixas", "grade e vidro", "medida e requadro"],
    source: "Catálogo enviado",
  },
  {
    id: "lucasa-doors",
    brand: "lucasa",
    family: "Portas",
    title: "Portas Lucasa",
    code: "catálogo oficial online · modelo e acabamento a confirmar",
    spec: "Portas da marca Ullian/Lucasa para diferentes ambientes; o canal oficial organiza a escolha por necessidade e ambiente.",
    bestFor: "Entrada, sala, dormitório e cliente que busca segurança, conforto e aparência de produto acabado.",
    pitch: "Posso usar a Lucasa quando o cliente quer comparar design e conforto, mas vou confirmar o modelo exato e a composição antes de fechar.",
    checks: ["modelo e linha", "medida e abertura", "cor/vidro", "disponibilidade e prazo"],
    source: "Site oficial (catálogo não anexado)",
  },
  {
    id: "lucasa-windows",
    brand: "lucasa",
    family: "Janelas",
    title: "Janelas Lucasa",
    code: "entrada, cozinha, sala, dormitório, lavanderia e banheiro",
    spec: "Janelas organizadas por ambiente e necessidade, com apelo de iluminação natural, conforto térmico, proteção e durabilidade.",
    bestFor: "Cliente que quer melhorar luz, ventilação, segurança ou conforto em um ambiente específico.",
    pitch: "Em vez de mandar todas as opções, eu começo pelo ambiente e pelo que falta nele: luz, ventilação, privacidade ou conforto.",
    checks: ["ambiente e função", "tipo de abertura", "medida e cor", "vidro, grade e prazo"],
    source: "Site oficial (catálogo não anexado)",
  },
  {
    id: "lucasa-performance",
    brand: "lucasa",
    family: "Argumentos de valor",
    title: "Conforto, proteção e durabilidade",
    code: "pontos do canal oficial; validar no modelo escolhido",
    spec: "O site oficial destaca proteção contra chuva e vento, conforto térmico, luminosidade, resistência e durabilidade à ação do tempo.",
    bestFor: "Cliente que compara somente por preço e precisa entender desempenho e uso no ambiente.",
    pitch: "A comparação não precisa ser só pelo valor: vamos ver o que muda em proteção, conforto, luz e durabilidade no modelo específico.",
    checks: ["modelo que sustenta o argumento", "desempenho aplicável", "composição e instalação", "garantia vigente"],
    source: "Site oficial (catálogo não anexado)",
  },
  {
    id: "riobras-doors",
    brand: "riobras",
    family: "Portas",
    title: "Portas Riobras",
    code: "catálogo oficial online · custo-benefício",
    spec: "Portas da marca Ullian/Riobras pensadas para eficiência, praticidade, conforto e segurança, com modelos a confirmar pelo catálogo vigente.",
    bestFor: "Cliente que quer uma solução objetiva e está comparando custo-benefício.",
    pitch: "A Riobras entra quando o custo-benefício pesa, mas eu ainda vou igualar medida, abertura e composição para a comparação ser justa.",
    checks: ["modelo e abertura", "medida e cor", "vidro/ferragens", "prazo e disponibilidade"],
    source: "Site oficial (catálogo não anexado)",
  },
  {
    id: "riobras-windows",
    brand: "riobras",
    family: "Janelas",
    title: "Janelas Riobras",
    code: "cozinha, sala, dormitório, lavanderia e banheiro",
    spec: "Janelas para diferentes ambientes, com foco de comunicação em iluminação, conforto térmico, proteção e durabilidade.",
    bestFor: "Obra residencial ou de volume que busca uma alternativa funcional e comparável.",
    pitch: "Vou separar a opção Riobras pelo uso do ambiente e pela medida, para você comparar custo-benefício sem misturar produtos diferentes.",
    checks: ["ambiente", "tipo de abertura e folhas", "medida e cor", "grade, vidro e prazo"],
    source: "Site oficial (catálogo não anexado)",
  },
];
