-- All data and password proofs live in a non-exposed schema. The browser uses
-- the Edge Function; only its private service_role can execute the RPC facade.
create schema if not exists mp_shared_private;
revoke all on schema mp_shared_private from public, anon, authenticated;
grant usage on schema mp_shared_private to service_role;

create table if not exists mp_shared_private.users (
  id bigint generated by default as identity primary key check (id between 1 and 9007199254740991),
  username text not null check (username ~ '^[a-zA-Z0-9._-]{3,40}$'),
  username_normalized text not null check (username_normalized = lower(username) and username_normalized <> 'admin'),
  display_name text not null check (char_length(display_name) between 2 and 80),
  branch text not null check (branch in ('Araraquara', 'São Carlos')),
  password_proof jsonb not null,
  session_version text not null default gen_random_uuid()::text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);
create unique index if not exists mp_users_live_username on mp_shared_private.users(username_normalized) where deleted_at is null;
create table if not exists mp_shared_private.user_state (
  user_id bigint primary key references mp_shared_private.users(id),
  state jsonb,
  client_state jsonb not null default '{"schemaVersion":1}'::jsonb,
  revision text not null,
  updated_at timestamptz not null default now(),
  check (state is null or jsonb_typeof(state) = 'object'),
  check (jsonb_typeof(client_state) = 'object'),
  check (octet_length(coalesce(state::text,'')) <= 500000),
  check (octet_length(client_state::text) <= 180000)
);
create table if not exists mp_shared_private.sessions (
  token_hash text primary key check (token_hash ~ '^[0-9a-f]{64}$'),
  role text not null check (role in ('user','admin')),
  user_id bigint references mp_shared_private.users(id),
  user_version text not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  revoked_at timestamptz,
  check ((role = 'user' and user_id is not null) or (role = 'admin' and user_id is null))
);
create index if not exists mp_sessions_user on mp_shared_private.sessions(user_id);
create index if not exists mp_sessions_expiry on mp_shared_private.sessions(expires_at);
create table if not exists mp_shared_private.rate_limits (
  bucket text primary key check (bucket ~ '^[0-9a-f]{64}$'),
  window_start timestamptz not null,
  attempts bigint not null check (attempts >= 0)
);
create index if not exists mp_rate_limits_time on mp_shared_private.rate_limits(window_start);
create table if not exists mp_shared_private.access_config (
  id boolean primary key default true check (id),
  proof jsonb not null,
  updated_at timestamptz not null default now()
);
create table if not exists mp_shared_private.import_batches (
  batch_id text primary key,
  digest text not null check (digest ~ '^[0-9a-f]{64}$'),
  result jsonb not null,
  created_at timestamptz not null default now()
);
create table if not exists mp_shared_private.import_records (
  source_id text primary key,
  digest text not null check (digest ~ '^[0-9a-f]{64}$'),
  username_normalized text not null,
  user_id bigint references mp_shared_private.users(id),
  result jsonb not null,
  created_at timestamptz not null default now()
);

alter table mp_shared_private.users enable row level security;
alter table mp_shared_private.user_state enable row level security;
alter table mp_shared_private.sessions enable row level security;
alter table mp_shared_private.rate_limits enable row level security;
alter table mp_shared_private.access_config enable row level security;
alter table mp_shared_private.import_batches enable row level security;
alter table mp_shared_private.import_records enable row level security;
-- No policies for anon/authenticated: no access, even if an exposed schema is
-- accidentally configured later. Explicit grants also reject direct queries.
revoke all on all tables in schema mp_shared_private from public, anon, authenticated;
revoke all on all sequences in schema mp_shared_private from public, anon, authenticated;
grant select, insert, update, delete on all tables in schema mp_shared_private to service_role;
grant usage, select on all sequences in schema mp_shared_private to service_role;

create or replace function mp_shared_private.merge_client_progress(p_base jsonb, p_incoming jsonb)
returns jsonb language plpgsql security invoker set search_path = '' as $$
declare
  v_result jsonb := coalesce(p_base, '{"schemaVersion":1}'::jsonb);
  v_resume jsonb;
  v_brands jsonb := coalesce(v_result->'brands','{}'::jsonb);
  v_brand text;
  v_entry jsonb;
  v_current jsonb;
  v_merged jsonb;
begin
  if p_incoming ? 'resume' then
    v_resume := coalesce(v_result->'resume','{}'::jsonb) || (p_incoming->'resume');
    if (p_incoming->'resume') ? 'factoryWizardDraft' then
      v_resume := jsonb_set(v_resume,'{factoryWizardDraft}',
        coalesce(v_result->'resume'->'factoryWizardDraft','{}'::jsonb) || (p_incoming->'resume'->'factoryWizardDraft'));
    end if;
    v_result := jsonb_set(v_result,'{resume}',v_resume);
  end if;
  if p_incoming ? 'brands' then
    for v_brand,v_entry in select key,value from jsonb_each(p_incoming->'brands') loop
      v_current := coalesce(v_brands->v_brand,'{}'::jsonb);
      v_merged := v_current || v_entry;
      if v_entry ? 'learning' then
        -- Answers are an explicit replacement: {} means reset the exercise.
        v_merged := jsonb_set(v_merged,'{learning}',coalesce(v_current->'learning','{}'::jsonb) || (v_entry->'learning'));
      end if;
      if v_entry ? 'studySheet' then
        v_merged := jsonb_set(v_merged,'{studySheet}',coalesce(v_current->'studySheet','{}'::jsonb) || (v_entry->'studySheet'));
      end if;
      v_brands := jsonb_set(v_brands,array[v_brand],v_merged);
    end loop;
    v_result := jsonb_set(v_result,'{brands}',v_brands);
  end if;
  return v_result || '{"schemaVersion":1}'::jsonb;
end;
$$;
revoke all on function mp_shared_private.merge_client_progress(jsonb,jsonb) from public, anon, authenticated;
grant execute on function mp_shared_private.merge_client_progress(jsonb,jsonb) to service_role;

create or replace function public.mp_shared_set_access_proof(p_proof jsonb)
returns jsonb language plpgsql security invoker set search_path = '' as $$
begin
  if jsonb_typeof(p_proof) <> 'object'
    or p_proof->>'version' is distinct from 'pbkdf2-sha256-v1'
    or coalesce(p_proof->>'salt','') !~ '^[A-Za-z0-9+/]{22}==$'
    or coalesce(p_proof->>'hash','') !~ '^[A-Za-z0-9+/]{43}=$'
    or coalesce(p_proof->>'iterations','') !~ '^\d+$'
    or (p_proof->>'iterations')::bigint not between 100000 and 1000000
    or octet_length(decode(p_proof->>'salt','base64')) <> 16
    or octet_length(decode(p_proof->>'hash','base64')) <> 32 then
    raise exception 'Invalid password proof' using errcode = '22023';
  end if;
  insert into mp_shared_private.access_config (id, proof) values (true, p_proof)
  on conflict (id) do update set proof = excluded.proof, updated_at = clock_timestamp();
  update mp_shared_private.sessions set revoked_at = clock_timestamp() where role = 'admin' and revoked_at is null;
  return jsonb_build_object('configured', true);
end;
$$;
revoke all on function public.mp_shared_set_access_proof(jsonb) from public, anon, authenticated;
grant execute on function public.mp_shared_set_access_proof(jsonb) to service_role;

-- A single transaction is the authority for protected operations, including
-- session validation, owner checks, data CAS, account rotation and import.
create or replace function public.mp_shared_store(p_action text, p_payload jsonb default '{}'::jsonb, p_auth jsonb default null)
returns jsonb language plpgsql security invoker set search_path = '' as $$
declare
  v_now timestamptz := clock_timestamp();
  v_session mp_shared_private.sessions%rowtype;
  v_user mp_shared_private.users%rowtype;
  v_target mp_shared_private.users%rowtype;
  v_state mp_shared_private.user_state%rowtype;
  v_count bigint;
  v_window timestamptz;
  v_seconds integer;
  v_max integer;
  v_client_state jsonb;
  v_existing jsonb;
  v_result jsonb;
  v_entry jsonb;
  v_results jsonb := '[]'::jsonb;
  v_imported integer := 0;
  v_conflicts integer := 0;
  v_batch_digest text;
begin
  if jsonb_typeof(p_payload) <> 'object' then
    raise exception 'Invalid payload' using errcode = '22023';
  end if;
  if p_action in ('resolve_session','get_state','save_state','update_user','list_users','get_user_detail',
      'admin_create_user','admin_update_user','delete_user','import_local') then
    select * into v_session from mp_shared_private.sessions
      where token_hash = p_auth->>'tokenHash' and revoked_at is null and expires_at > v_now
      ;
    if not found then return '{"status":"unauthorized"}'::jsonb; end if;
    if v_session.role = 'user' then
      -- Lock the user before its state. Password reset/delete then serialize
      -- with this transaction and cannot leave an old session writing data.
      select * into v_user from mp_shared_private.users
        where id = v_session.user_id and deleted_at is null and session_version = v_session.user_version
        for update;
      if not found then return '{"status":"unauthorized"}'::jsonb; end if;
    elsif v_session.user_version is distinct from p_auth->>'adminVersion'
      or coalesce(p_auth->>'adminVersion','') = '' then
      return '{"status":"unauthorized"}'::jsonb;
    end if;
    -- Re-check after acquiring the user lock, then lock the session. Account
    -- writes use this same user -> session order, avoiding lock-upgrade and
    -- reset/delete deadlocks between devices.
    select * into v_session from mp_shared_private.sessions
      where token_hash = p_auth->>'tokenHash' and revoked_at is null and expires_at > clock_timestamp() for share;
    if not found then return '{"status":"unauthorized"}'::jsonb; end if;
    if v_session.role = 'user' and v_user.session_version is distinct from v_session.user_version then
      return '{"status":"unauthorized"}'::jsonb;
    end if;
    if p_action in ('list_users','get_user_detail','admin_create_user','admin_update_user','delete_user','import_local')
       and v_session.role <> 'admin' then return '{"status":"forbidden"}'::jsonb; end if;
    if p_action in ('get_state','save_state','update_user')
       and (v_session.role <> 'user' or v_session.user_id is distinct from (p_payload->>'userId')::bigint) then
      return '{"status":"forbidden"}'::jsonb;
    end if;
  end if;

  if p_action = 'get_access_proof' then
    return jsonb_build_object('proof', (select proof from mp_shared_private.access_config where id));
  elsif p_action = 'rate_limit' then
    v_seconds := greatest(1, least((p_payload->>'seconds')::integer, 86400));
    v_max := greatest(1, least((p_payload->>'max')::integer, 100000));
    insert into mp_shared_private.rate_limits (bucket, window_start, attempts)
      values (p_payload->>'bucket', v_now, 1)
    on conflict (bucket) do update set
      attempts = case when mp_shared_private.rate_limits.window_start + make_interval(secs => v_seconds) <= v_now
        then 1 else least(mp_shared_private.rate_limits.attempts + 1, 1000000000) end,
      window_start = case when mp_shared_private.rate_limits.window_start + make_interval(secs => v_seconds) <= v_now
        then v_now else mp_shared_private.rate_limits.window_start end
    returning attempts, window_start into v_count, v_window;
    delete from mp_shared_private.rate_limits where window_start < v_now - interval '2 days';
    return jsonb_build_object('allowed', v_count <= v_max,
      'retryAfter', greatest(1, ceil(extract(epoch from (v_window + make_interval(secs => v_seconds) - v_now)))::integer));
  elsif p_action = 'get_user_by_username' then
    select * into v_user from mp_shared_private.users
      where username_normalized = p_payload->>'usernameNormalized' and deleted_at is null;
    return jsonb_build_object('user', case when v_user.id is null then null else jsonb_build_object(
      'id',v_user.id,'username',v_user.username,'usernameNormalized',v_user.username_normalized,
      'displayName',v_user.display_name,'branch',v_user.branch,'password',v_user.password_proof,
      'sessionVersion',v_user.session_version,'createdAt',v_user.created_at) end);
  elsif p_action = 'resolve_session' then
    return jsonb_build_object('session', jsonb_build_object('role',v_session.role,'userId',v_session.user_id,'expiresAt',v_session.expires_at),
      'user', case when v_user.id is null then null else jsonb_build_object(
        'id',v_user.id,'username',v_user.username,'usernameNormalized',v_user.username_normalized,
        'displayName',v_user.display_name,'branch',v_user.branch,'password',v_user.password_proof,
        'sessionVersion',v_user.session_version,'createdAt',v_user.created_at) end);
  elsif p_action = 'create_session' then
    if p_payload->>'role' = 'user' then
      select * into v_user from mp_shared_private.users where id = (p_payload->>'userId')::bigint
        and deleted_at is null and session_version = p_payload->>'version' for share;
      if not found then return '{"status":"version-conflict"}'::jsonb; end if;
    end if;
    insert into mp_shared_private.sessions (token_hash,role,user_id,user_version,created_at,expires_at)
      values (p_payload->>'tokenHash',p_payload->>'role',(p_payload->>'userId')::bigint,
        p_payload->>'version',v_now,(p_payload->>'expiresAt')::timestamptz);
    delete from mp_shared_private.sessions where expires_at < v_now - interval '7 days';
    return '{"ok":true}'::jsonb;
  elsif p_action = 'revoke_session' then
    update mp_shared_private.sessions set revoked_at = v_now where token_hash = p_payload->>'tokenHash';
    return '{"ok":true}'::jsonb;
  elsif p_action in ('create_user','admin_create_user') then
    insert into mp_shared_private.users (username,username_normalized,display_name,branch,password_proof)
      values (p_payload->>'username',p_payload->>'usernameNormalized',p_payload->>'displayName',p_payload->>'branch',p_payload->'password')
      on conflict (username_normalized) where deleted_at is null do nothing returning * into v_user;
    if not found then return '{"status":"username-conflict"}'::jsonb; end if;
    return jsonb_build_object('user', jsonb_build_object('id',v_user.id,'username',v_user.username,
      'usernameNormalized',v_user.username_normalized,'displayName',v_user.display_name,'branch',v_user.branch,
      'sessionVersion',v_user.session_version,'createdAt',v_user.created_at));
  elsif p_action = 'get_state' then
    select * into v_state from mp_shared_private.user_state where user_id = v_session.user_id;
    return jsonb_build_object('state',v_state.state,'revision',v_state.revision,
      'clientState',coalesce(v_state.client_state,'{"schemaVersion":1}'::jsonb));
  elsif p_action = 'save_state' then
    -- A lock on the user also serializes the first save when no state row exists.
    perform 1 from mp_shared_private.users where id = v_session.user_id for update;
    select * into v_state from mp_shared_private.user_state where user_id = v_session.user_id for update;
    v_client_state := case when p_payload ? 'clientState' then mp_shared_private.merge_client_progress(v_state.client_state,p_payload->'clientState')
      else coalesce(v_state.client_state,'{"schemaVersion":1}'::jsonb) end;
    if octet_length(v_client_state::text) > 150000 then return '{"status":"progress-too-large"}'::jsonb; end if;
    if not (p_payload ? 'baseRevision') or (p_payload->>'baseRevision') is distinct from v_state.revision then
      if v_state.user_id is not null and v_state.state = p_payload->'state' and v_state.client_state = v_client_state then
        return jsonb_build_object('ok',true,'revision',v_state.revision);
      end if;
      return jsonb_build_object('status','state-conflict','revision',v_state.revision);
    end if;
    insert into mp_shared_private.user_state (user_id,state,client_state,revision,updated_at)
      values (v_session.user_id,p_payload->'state',v_client_state,p_payload->>'revision',v_now)
      on conflict (user_id) do update set state = excluded.state, client_state = excluded.client_state,
        revision = excluded.revision, updated_at = excluded.updated_at;
    return jsonb_build_object('ok',true,'revision',p_payload->>'revision');
  elsif p_action in ('update_user','admin_update_user') then
    select * into v_target from mp_shared_private.users where id = (p_payload->>'userId')::bigint and deleted_at is null for update;
    if not found then return '{"status":"not-found"}'::jsonb; end if;
    if p_action = 'update_user' and v_target.session_version is distinct from p_payload->>'expectedVersion' then
      return '{"status":"version-conflict"}'::jsonb;
    end if;
    if exists(select 1 from mp_shared_private.users where username_normalized = p_payload->>'usernameNormalized' and id <> v_target.id and deleted_at is null) then
      return '{"status":"username-conflict"}'::jsonb;
    end if;
    update mp_shared_private.users set username = p_payload->>'username',
      username_normalized = p_payload->>'usernameNormalized', display_name = p_payload->>'displayName', branch = p_payload->>'branch',
      password_proof = case when jsonb_typeof(p_payload->'password') = 'object' then p_payload->'password' else password_proof end,
      session_version = gen_random_uuid()::text, updated_at = v_now where id = v_target.id returning * into v_user;
    update mp_shared_private.sessions set revoked_at = v_now where user_id = v_user.id and revoked_at is null;
    return jsonb_build_object('user', jsonb_build_object('id',v_user.id,'username',v_user.username,
      'usernameNormalized',v_user.username_normalized,'displayName',v_user.display_name,'branch',v_user.branch,
      'sessionVersion',v_user.session_version,'createdAt',v_user.created_at));
  elsif p_action = 'delete_user' then
    update mp_shared_private.users set deleted_at = v_now, session_version = gen_random_uuid()::text, updated_at = v_now
      where id = (p_payload->>'userId')::bigint and deleted_at is null returning * into v_target;
    if not found then return '{"status":"not-found"}'::jsonb; end if;
    update mp_shared_private.sessions set revoked_at = v_now where user_id = v_target.id and revoked_at is null;
    -- Retain the original state for recovery; no client has access after removal.
    return jsonb_build_object('ok',true,'id',v_target.id);
  elsif p_action = 'list_users' then
    select coalesce(jsonb_agg(jsonb_build_object('id',u.id,'username',u.username,'displayName',u.display_name,'branch',u.branch,
      'createdAt',u.created_at,'dataUpdatedAt',s.updated_at,'state',s.state) order by u.id desc),'[]'::jsonb)
      into v_results from mp_shared_private.users u left join mp_shared_private.user_state s on s.user_id = u.id where u.deleted_at is null;
    return jsonb_build_object('users',v_results);
  elsif p_action = 'get_user_detail' then
    select * into v_target from mp_shared_private.users where id = (p_payload->>'userId')::bigint and deleted_at is null;
    if not found then return '{"status":"not-found"}'::jsonb; end if;
    select * into v_state from mp_shared_private.user_state where user_id = v_target.id;
    return jsonb_build_object('user',jsonb_build_object('id',v_target.id,'username',v_target.username,'displayName',v_target.display_name,
      'branch',v_target.branch,'createdAt',v_target.created_at,'dataUpdatedAt',v_state.updated_at,'state',v_state.state,
      'clientState',coalesce(v_state.client_state,'{"schemaVersion":1}'::jsonb)));
  elsif p_action = 'import_local' then
    -- Serialize matching batches and sources before reading, preventing two
    -- overlapping imports from creating divergent identity mappings.
    perform pg_advisory_xact_lock(hashtextextended('mp-import-global',0));
    select digest,result into v_batch_digest,v_existing from mp_shared_private.import_batches where batch_id = p_payload->>'batchId';
    if found then
      if v_batch_digest is distinct from p_payload->>'digest' then return '{"status":"batch-conflict"}'::jsonb; end if;
      return v_existing;
    end if;
    if jsonb_typeof(p_payload->'records') <> 'array' or jsonb_array_length(p_payload->'records') not between 1 and 120 then
      raise exception 'Invalid import' using errcode = '22023';
    end if;
    for v_entry in select value from jsonb_array_elements(p_payload->'records') loop
      select result,digest into v_existing,v_batch_digest from mp_shared_private.import_records where source_id = v_entry->>'sourceId';
      if found then
        if v_batch_digest = v_entry->>'digest' and v_existing->>'status' = 'imported'
          and exists(select 1 from mp_shared_private.users where id = (v_existing->>'userId')::bigint and deleted_at is null) then
          v_result := v_existing || '{"status":"already-imported"}'::jsonb;
        else
          v_result := jsonb_build_object('sourceId',v_entry->>'sourceId','username',v_entry->>'username','status','conflict');
          v_conflicts := v_conflicts + 1;
        end if;
      else
        insert into mp_shared_private.users (username,username_normalized,display_name,branch,password_proof)
          values (v_entry->>'username',v_entry->>'usernameNormalized',v_entry->>'displayName',v_entry->>'branch',v_entry->'password')
          on conflict (username_normalized) where deleted_at is null do nothing returning * into v_target;
        if found then
          if jsonb_typeof(v_entry->'state') = 'object' or v_entry->'clientState' <> '{"schemaVersion":1}'::jsonb then
            insert into mp_shared_private.user_state (user_id,state,client_state,revision,updated_at)
              values (v_target.id, nullif(v_entry->'state','null'::jsonb),v_entry->'clientState',v_now::text || '|' || gen_random_uuid()::text,v_now);
          end if;
          v_result := jsonb_build_object('sourceId',v_entry->>'sourceId','username',v_entry->>'username','status','imported','userId',v_target.id);
          v_imported := v_imported + 1;
        else
          v_result := jsonb_build_object('sourceId',v_entry->>'sourceId','username',v_entry->>'username','status','conflict');
          v_conflicts := v_conflicts + 1;
        end if;
        insert into mp_shared_private.import_records (source_id,digest,username_normalized,user_id,result)
          values (v_entry->>'sourceId',v_entry->>'digest',v_entry->>'usernameNormalized',case when v_result->>'status' = 'imported' then v_target.id else null end,v_result);
      end if;
      v_results := v_results || jsonb_build_array(v_result);
    end loop;
    v_result := jsonb_build_object('results',v_results,'imported',v_imported,'conflicts',v_conflicts);
    insert into mp_shared_private.import_batches (batch_id,digest,result) values (p_payload->>'batchId',p_payload->>'digest',v_result);
    return v_result;
  end if;
  raise exception 'Unknown store action' using errcode = '22023';
end;
$$;
revoke all on function public.mp_shared_store(text,jsonb,jsonb) from public, anon, authenticated;
grant execute on function public.mp_shared_store(text,jsonb,jsonb) to service_role;
